### ISSUE TITLE
Model is bigger than in the example

### ISSUE THREAD

**Issue by pnavaro** [GLambard/SMILES-X#7]
Dear Guillaume,

Thank you very much for sharing this. I try to run the notebook and I have some issues with the size of the problem. It is much bigger than yours and I use the same parameters. do you have an idea of what happened ?

My executed notebook
https://github.com/pnavaro/SMILES-X/blob/master/SMILESX_Prediction_github.ipynb

```
***Bayesian Optimization of the SMILESX's architecture.***

Random initialization:

Model: [[512.  512.   32.  128.    3.9]]
```

Best regards
Pierre

**Comment by GLambard** [comment]
Dear Pierre, 

Thank you for your interest in the SMILES-X. 

Also, what do you mean by the size of the problem? 

I have checked your notebook, and I don't see any particular issue apart from the one possibly coming from a versioning problem that can be ignored so far. 

Best.

**Comment by pnavaro** [comment]
Thank you for your response.

It was difficult to install tensorflow v1 with last versions of cuda toolkit and cuddn so I will try to upgrade to tensorflow v2. Before that I want to be sure that my computation is good. 
Thank you for reassuring me.
